"""empty message

Revision ID: 5e94908dd26f
Revises: cd4a3c5489a0
Create Date: 2025-03-08 23:54:17.654130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e94908dd26f'
down_revision = 'cd4a3c5489a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_roll')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('_alembic_tmp_roll',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('note', sa.VARCHAR(length=64), nullable=False),
    sa.Column('amount', sa.INTEGER(), nullable=False),
    sa.Column('dice_number', sa.INTEGER(), nullable=False),
    sa.Column('roll_result', sa.VARCHAR(length=999), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
